### ISSUE TITLE
Wither Skeletons Missing 

### ISSUE THREAD

**Issue by Crudedragos** [ProjectZulu/JustAnotherSpawner#137]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288431-just-another-spawner-jas-v0-14?comment=2149

**Comment by Taschenmogul** [comment]
Hm, just stopped by after a while and this reminded me of an issue a player had on my server perhaps two months ago. He too was complaining about no wither skeletons being spawned, having explored nether fortresses for hours.
So I set out and did a little testing, drastically increasing skeleton spawn weight for nether bridges, killing all monsters and waiting for them to respawn. I was able to get some skeletons (and wither skeletons) to spawn so that from my experience I can tell that they do spawn occasionally, though sadly not reliably.

Now my theory was this:

Given the relatively small area offered by a nether bridge/fortress for it's structure-specific entities to spawn compared to the relatively huge area of the surrounding biomes, the chance that an entity spawned in the chunks loaded by a player would be spawned at a location with a nether bridge structure would already be low.
Assuming that structure-specific spawn entries are just added to the list of valid spawns for the underlying biome for that coordinate, the default spawn weight of 10 for skeletons in the "nether bridge" structure compared to weights like 100 for zombie pigmen in the nether biomes would further make it improbable that a spawned entity would be a skeleton.

Combined with the entity cap this would then mean that by the time a player would reach a nether fortress there would already be so many spawned monsters around that some would have to despawn first for the skeletons to even get the opportunity to spawn, and that even when this would happen the chance that a monster would spawn at the position of a nether fortress and that this monster would be a skeleton would be so miniscule that spawning of skeletons could be considered effectively prevented.

Now this is just a theory and I don't know if it's correct, especially as I don't really know how JAS handles structure spawns. Given that nobody else has commented on this issue here I thought my experiences might still be of some diffuse help though.

**Comment by Crudedragos** [comment]
@Taschenmogul Good theory. Only caveat is that the two spawns lists are not combined, The nether bridge structure spawnlists replaces the biome spawnlist at the location considered "nether bridge". Where to spawn is selected randomly from the world and is structure/biome independent.

The caps are shared though which causes the problem. Running /killall a few times i'd see 4-5 withers spawn in a cap of ~75.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288431-just-another-spawner-jas-v0-14?comment=2235
